# targets: prerequisites
#	command
#	command
#	command
#
# targets is the name of the file and will be created if it no where to be found
# Prerequisites are dependicies. If the target is found, it will check prerequisite if the modified date is newer
# Commands are bash commands that will be executed 
# IMPORTANT, it has to be TAB and not SPACEs for the command
blah: blah.cpp
	g++ blah.cpp -o blah